### ISSUE TITLE
Initial Syncloud user is not in Nextcloud "admin" group

### ISSUE THREAD

**Issue by mikini** [syncloud/platform#579]
**Describe the bug**
After initial installation of latest image downloaded today for Raspberry 3B I struggled finding any clue on how to access the Admin UI for installing/reviewing Nextcloud Apps

Hunt through official Syncloud & eventually Nextcloud  docs. and forum said just "[left panel under settings](https://help.nextcloud.com/t/cant-find-admin-page/87975)" but nothing was there for the initial user.

However, [another post](https://help.nextcloud.com/t/cannot-find-admin-page-after-install/86934/5) revealed the existence of a Nextcloud "admin" user group which had no members on the soundcloud installation, but which gained me access to admin UI when I remembered having seen some very subtly hinted "fix rights" LDAP mapping sql commands from the [Nextcloud wiki page](https://github.com/syncloud/platform/wiki/Nextcloud).

```
# snap run nextcloud.occ group:list
  - admin:
  - syncloud:
    - <syncloud initial user> 
# snap run nextcloud.psql -c "update oc_ldap_group_mapping set owncloud_name = 'admin'"
could not change directory to "/root": Permission denied
UPDATE 1
# snap run nextcloud.psql -c "update oc_ldap_group_members set owncloudname = 'admin'"
could not change directory to "/root": Permission denied
UPDATE 1
# snap run nextcloud.occ group:list
  - admin:
    - <syncloud initial user> 
#
```
This ought to be more clearly documented as a required procedure after installation until it is fixed properly to do the right thing during installation.
